### PR TITLE
⬆️ Upgraded to 1.19.2

### PR DESCRIPTION
**Pull request by CephalonCosmic**
Rip chat signing

### CODE REVIEW

**Comment by CephalonCosmic** [comment]
#7

**Comment by gobletm** [comment]
Hey since you made an update to 1.19.2 and the owner does not respond, why not make a fork?

**Comment by apace100** [comment]
Hi there! What are the changes in the GitHub workflow and the build.gradle for?
Otherwise, thanks for the PR. :) I myself tried integrating the chat signing somehow, so that SMWYG messages show up as secure, but since that proved more difficult than expected, this should do for an update.
I'll integrate it once you reply regarding the non-feature changes I'm confused about.

**Comment by CephalonCosmic** [comment]
Hai! The changes to the `build.gradle` was to update fabric-loom to the latest version and add a developer mod for allowing to login with an account in dev environment. The change in the GitHub workflow was to manually trigger the action, this can be reverted safely. we are currently using this the server's modpack https://modrinth.com/modpack/devos-season-5

**Comment by apace100** [comment]
Alright. :) Thanks for the info.
Since the changes compared to 1.19.0 are quite large, could you retarget the PR to the new 1.19.x branch I just created?

**Pull request merged**
